ex 1 :


In [1]:
import numpy as np

In [4]:
def create_arr(start,step,length):
    return np.arange(start,(length * step)+ step, step )

In [7]:
x = np.array(range(6,404,4))


In [8]:
x

array([  6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,
        58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106,
       110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158,
       162, 166, 170, 174, 178, 182, 186, 190, 194, 198, 202, 206, 210,
       214, 218, 222, 226, 230, 234, 238, 242, 246, 250, 254, 258, 262,
       266, 270, 274, 278, 282, 286, 290, 294, 298, 302, 306, 310, 314,
       318, 322, 326, 330, 334, 338, 342, 346, 350, 354, 358, 362, 366,
       370, 374, 378, 382, 386, 390, 394, 398, 402])

In [9]:
x.shape

(100,)

In [10]:
x2 = create_arr(6,4,100)

In [11]:
x2

array([  6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,
        58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106,
       110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158,
       162, 166, 170, 174, 178, 182, 186, 190, 194, 198, 202, 206, 210,
       214, 218, 222, 226, 230, 234, 238, 242, 246, 250, 254, 258, 262,
       266, 270, 274, 278, 282, 286, 290, 294, 298, 302, 306, 310, 314,
       318, 322, 326, 330, 334, 338, 342, 346, 350, 354, 358, 362, 366,
       370, 374, 378, 382, 386, 390, 394, 398, 402])

ex 2 :


In [13]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)

[ 1.  2.  3. nan  5.  6.  7. nan]


In [14]:
np.isnan(a)

array([False, False, False,  True, False, False, False,  True])

In [15]:
a > 2

array([False, False,  True, False,  True,  True,  True, False])

In [16]:
a % 2 == 0

array([False,  True, False, False, False,  True, False, False])

In [18]:
a[np.isnan(a)]

array([nan, nan])

In [19]:
a[ a> 2]

array([3., 5., 6., 7.])

ex 3 :

In [22]:
x = np.random.randint(100, size = (5,6))

In [23]:
x

array([[93, 93, 39, 25, 81, 20],
       [14,  1, 18, 28, 45, 28],
       [56,  5, 94, 54, 46, 15],
       [33, 23, 68,  1, 26, 61],
       [40, 59, 94, 37, 77,  2]])

In [24]:
np.max(x)

94